from schemas.state import AgentState


def create_initial_state(query: str) -> AgentState:

    return {
        "query": query,
        "plan": [],
        "subtasks": [],
        "search_results": {},
        "research_notes": {},
        "draft_report": "",
        "final_report": "",
        "critique": "",
        "iteration_count": 0,
        "memory_context": [],
        "citations": [],
        "webpage_content": {},
        "filtered_content": {},
        "needs_revision": False,
        "search_queries": [],
        "boss_strategy": "",
        "completed_tasks": [],
        "research_progress": {}, 
        "additional_tasks": [],
        "available_tools": [],
        "tool_results": {},   
        "selected_tools": [],    
        "task_assignments": {},
        "worker_tools": {},
        "knowledge_graph_updates": [],
        "entity_extractions": [],
        "quality_scores": {},
        "needs_more_research": False,
        "tool_execution_results": {},
        "github_results": {},
        "reddit_results": {},
        "youtube_results": {},
        "exa_results": {},
        "twitter_results": {},
        "rss_results": {},
        "linkedin_results": {},
        "unified_research": {},
    }